// Child metadata mapping derived from the same Salesforce registry snapshot as
// src/api/git-metadata-types.ts. Apache-2.0; see THIRD_PARTY_NOTICES.md.
export const childMetadataTypes = [
  {"name": "AIScoringModelDefVersion", "parent": "AIScoringModelDefinition", "directory": "aiScoringModelDefinitions", "suffix": "aiScoringModelDefinition", "element": "aiScoringModelDefVersions", "identity": "fullName", "ignoreParentName": false},
  {"name": "AssignmentRule", "parent": "AssignmentRules", "directory": "assignmentRules", "suffix": "assignmentRules", "element": "assignmentRule", "identity": "fullName", "ignoreParentName": false},
  {"name": "AutoResponseRule", "parent": "AutoResponseRules", "directory": "autoResponseRules", "suffix": "autoResponseRules", "element": "autoResponseRule", "identity": "fullName", "ignoreParentName": false},
  {"name": "BotVersion", "parent": "Bot", "directory": "bots", "suffix": "bot", "element": "botVersions", "identity": "fullName", "ignoreParentName": false},
  {"name": "CustomLabel", "parent": "CustomLabels", "directory": "labels", "suffix": "labels", "element": "labels", "identity": "fullName", "ignoreParentName": true},
  {"name": "BusinessProcess", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "businessProcesses", "identity": "fullName", "ignoreParentName": false},
  {"name": "CompactLayout", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "compactLayouts", "identity": "fullName", "ignoreParentName": false},
  {"name": "CustomField", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "fields", "identity": "fullName", "ignoreParentName": false},
  {"name": "FieldSet", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "fieldSets", "identity": "fullName", "ignoreParentName": false},
  {"name": "Index", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "indexes", "identity": "fullName", "ignoreParentName": false},
  {"name": "ListView", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "listViews", "identity": "fullName", "ignoreParentName": false},
  {"name": "RecordType", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "recordTypes", "identity": "fullName", "ignoreParentName": false},
  {"name": "SharingReason", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "sharingReasons", "identity": "fullName", "ignoreParentName": false},
  {"name": "ValidationRule", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "validationRules", "identity": "fullName", "ignoreParentName": false},
  {"name": "WebLink", "parent": "CustomObject", "directory": "objects", "suffix": "object", "element": "webLinks", "identity": "fullName", "ignoreParentName": false},
  {"name": "DigitalExperience", "parent": "DigitalExperienceBundle", "directory": "digitalExperiences", "suffix": "digitalExperience", "element": "digitalExperiences", "identity": "fullName", "ignoreParentName": false},
  {"name": "EscalationRule", "parent": "EscalationRules", "directory": "escalationRules", "suffix": "escalationRules", "element": "escalationRule", "identity": "fullName", "ignoreParentName": false},
  {"name": "extDataTranFieldTemplate", "parent": "ExtDataTranObjectTemplate", "directory": "extDataTranObjectTemplates", "suffix": "extDataTranObjectTemplate", "element": "extDataTranFieldTemplates", "identity": "fullName", "ignoreParentName": false},
  {"name": "FormSection", "parent": "Form", "directory": "forms", "suffix": "form", "element": "formSections", "identity": "fullName", "ignoreParentName": false},
  {"name": "ManagedTopic", "parent": "ManagedTopics", "directory": "managedTopics", "suffix": "managedTopics", "element": "managedTopics", "identity": "fullName", "ignoreParentName": false},
  {"name": "MatchingRule", "parent": "MatchingRules", "directory": "matchingRules", "suffix": "matchingRule", "element": "matchingRules", "identity": "fullName", "ignoreParentName": false},
  {"name": "MktDataTranField", "parent": "MktDataTranObject", "directory": "mktDataTranObjects", "suffix": "mktDataTranObject", "element": "mktDataTranFields", "identity": "fullName", "ignoreParentName": false},
  {"name": "SharingCriteriaRule", "parent": "SharingRules", "directory": "sharingRules", "suffix": "sharingRules", "element": "sharingCriteriaRules", "identity": "fullName", "ignoreParentName": false},
  {"name": "SharingGuestRule", "parent": "SharingRules", "directory": "sharingRules", "suffix": "sharingRules", "element": "sharingGuestRules", "identity": "fullName", "ignoreParentName": false},
  {"name": "SharingOwnerRule", "parent": "SharingRules", "directory": "sharingRules", "suffix": "sharingRules", "element": "sharingOwnerRules", "identity": "fullName", "ignoreParentName": false},
  {"name": "SharingTerritoryRule", "parent": "SharingRules", "directory": "sharingRules", "suffix": "sharingRules", "element": "sharingTerritoryRules", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkflowAlert", "parent": "Workflow", "directory": "workflows", "suffix": "workflow", "element": "alerts", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkflowFieldUpdate", "parent": "Workflow", "directory": "workflows", "suffix": "workflow", "element": "fieldUpdates", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkflowFlowAction", "parent": "Workflow", "directory": "workflows", "suffix": "workflow", "element": "flowActions", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkflowKnowledgePublish", "parent": "Workflow", "directory": "workflows", "suffix": "workflow", "element": "knowledgePublishes", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkflowOutboundMessage", "parent": "Workflow", "directory": "workflows", "suffix": "workflow", "element": "outboundMessages", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkflowRule", "parent": "Workflow", "directory": "workflows", "suffix": "workflow", "element": "rules", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkflowSend", "parent": "Workflow", "directory": "workflows", "suffix": "workflow", "element": "send", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkflowTask", "parent": "Workflow", "directory": "workflows", "suffix": "workflow", "element": "tasks", "identity": "fullName", "ignoreParentName": false},
  {"name": "WorkSkillRoutingAttribute", "parent": "WorkSkillRouting", "directory": "workSkillRoutings", "suffix": "workSkillRouting", "element": "workSkillRoutingAttributes", "identity": "fullName", "ignoreParentName": false},
] as const;
